#!/bin/sh
#
# watcher.py watches for xhprof dumps and notifies perfbucket
#
# chkconfig:   - 80 20
# description: watches for xhprof dumps and notifies perfbucket

### BEGIN INIT INFO
# Provides: perfbucket-watcher
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Should-Start: 
# Should-Stop: 
# Default-Start: 
# Default-Stop: 
# Short-Description: start and stop perfbucket watcher
# Description: perfbucket watcher watches for xhprof dumps and notifies perfbucket
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

dumppath="/var/tmp/perfbucket"
exec="/opt/perfbucket/watcher.py"
prog="perfbucket-watcher"
apacheuser="wwwdata:wwwdata"
runuser="nobody"
pid_file="/var/run/perfbucket-watcher.pid"
pid=`ps ax | grep python26 | grep watcher.py | awk {'print $1'}`

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -f $exec ] || exit 5
    # ensure dumppath exists
    [ -d $dumppath ] || exit 5
    echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $exec"
    su -p -s /bin/sh $runuser -c "python26 $exec $dumppath" > /dev/null 2>&1 &
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile && echo $!>$pid_file && echo_success
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    [[ $pid != "" ]] && success && kill $pid || failure
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
